version: "3"

services:
  postgres:
    container_name: postgres
    build:
      context: db
      dockerfile: Dockerfile
    networks:
      - backend
    env_file:
      - .env
    ports:
      - 5432:5432
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    restart: always

  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 1337:1337
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

networks:
  backend:
    driver: bridge

#   frontend:
#     name: frontend_net
#     driver: bridge

volumes:
  postgres-data:
    name: postgres-data